# Version de docker-compose que se va a usar
version: '3'

services:
  # Nombre del servicio (Nombre deseado)
  support_api:
    # Nombre para el contenedor
    container_name: api_sopCubiq
    # Indica que en caso de que haya un fallo en el contenedor se reinicie
    restart: always
    # Indica que el constructor del contenedor esta en el directorio raiz de la app
    build: .
    # Puerto local : Puerto que expone la app
    ports:
      - "5000:5000"

    # Enlace con el contenedor mongo
    links:
      - mongo

    # Almacenamiento local (para que no se pierda la información)
    volumes:
      - .:/usr/src/app

  # Nombre del servicio (Nombre deseado)
  support_mongo:
    # Nombre para el contenedor
    container_name: db_sopCubiq
    # Nombre de la imagen para crear el contenedor (dockerHub)
    image: mongo
    # Puerto local : Puerto que expone la app
    ports:
    - "27017:27017"
    
    # Comando para silenciar logs de mongo en la consola
    command: mongod --quiet --logpath /dev/null 

    # NOTA: Una vez realizado todos los pasos para la construcción se ejecuta docker-compose buil y para la ejecución debe de ingresar el comando docker-compose up